### ISSUE TITLE
Author fields changed

### ISSUE THREAD

**Issue by handmade0octopus** [Crozin/Wykop.pl-Java-SDK#4]
This is 17th line in DeserializationUtils class is causing issues with working of API. There are probably some other changes in Wykop API that should be looked at.
	
//	authorFields.put("_avatar_big", "highQualityAvatar");

**Comment by Crozin** [comment]
I'll try to review changes made for the past 2 years to the API and fix all issues.

**Comment by Crozin** [comment]
Version `1.0.1` fixes the issue.
